import Head from "next/head";
import { useSession } from "next-auth/react";

const Home = () => {
  const { data } = useSession();

  return (
    <div className="flex flex-col p-0 items-center">
      <Head>
        <title>ZCal Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!!data?.user && <h1 className="font-bold text-4xl mb-8">Hi, {data.user.name}!</h1>}
      <h1 className="font-bold text-2xl">
        Welcome to ZcalClone, built with <code>Next.js</code> and <code>GraphQL</code>
      </h1>
    </div>
  );
};

export default Home;
