import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="flex p-0 justify-center">
      <Head>
        <title>ZCal Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="font-bold text-2xl my-8">
        Welcome to ZcalClone, built with <code>Next.js</code> and <code>GraphQL</code>
      </h1>
    </div>
  );
};

export default Home;
